---
title: "R Notebook"
output: html_notebook
---

SECTION 4.2.2: Gamma model


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
rm(list=ls())
```

```{r}
setwd("C:/Users/Simone/Downloads")

library(rjags)
library(caret)
library(ggmcmc)

options(scipen = 999)
```

```{r}
rm(list = ls())

CO2 <- read.csv("C:/Users/Simone/Downloads/CO2.csv")

#Eliminate Luxembourg from data, since it's an outlier for both GDP and CO2 and it represent a unique case that we aren't able to explain with our data
q=quantile(CO2$GDP,0.988)
p=quantile(CO2$co2percap, 0.988)
CO2 <- subset(CO2, CO2$GDP<q)
CO2 <- subset(CO2, CO2$co2percap<p)

```

A second general model, with equally uninformative prior and a fixed threshold, but using a gamma
model, was created, to check the findings of the first one and its
robustness. The results, reported below, brought to similar
consideration with respect to the ones for the original model, therefore
only the original model was considered later.

```{r}
#GENERAL WITH THRESHOLD GAMMA

model_string <- "
model {
  for (i in 1:N) {
    
    # Define the linear predictors, only for mu
    mu[i] <- inprod(X[i,], beta)
    
    #mu[i] <- beta_poor *X[i,1] +
    #         beta_rich *X[i,2] +
    #         beta_poor_gdp *X[i,3] +
    #         beta_rich_gdp *X[i,4] +
    #         beta_poor_EnergyUse *X[i,5] +
    #         beta_rich_EnergyUse *X[i,6] +
    #         beta_poor_urb *X[i,7] +
    #         beta_rich_urb *X[i,8] +
    #         beta_poor_internet *X[i,9] +
    #         beta_rich_internet *X[i,10] +

    #Normal model where the mean is modeled using the linear predictor, without further trasformations, for high interpretability
    co2percap[i] ~ dgamma(mu[i]+0.0001, beta_gamma)

    indicator[i] <- (unGDP[i] >= threshold)
    X[i, 1]   <-                (1 - indicator[i])
    X[i, 2]   <-                indicator[i]
    X[i, 3]   <- GDP[i]       * (1 - indicator[i])
    X[i, 4]   <- GDP[i]       * indicator[i]
    X[i, 5]   <- EnergyUse[i] * (1 - indicator[i])
    X[i, 6]   <- EnergyUse[i] * indicator[i]
    X[i, 7]   <- urb[i]       * (1 - indicator[i])
    X[i, 8]   <- urb[i]       * indicator[i]
    X[i, 9]   <- internet[i]  * (1 - indicator[i])
    X[i, 10]  <- internet[i]  * indicator[i]
    
  }

  #Prior for the variance
  beta_gamma ~ dgamma(0.001, 0.001)
  
  # Priors for beta parameters, beta[4] is the informative
  beta[1] ~ dnorm(0, 0.01)   #beta_poor
  beta[2] ~ dnorm(0, 0.01)   #beta_rich
  beta[3] ~ dnorm(1, 1)      #beta_poor_gdp
  beta[4] ~ dnorm(0, 1)      #beta_rich_gdp
  beta[5] ~ dnorm(0, 0.01)   #beta_poor_EnergyUse
  beta[6] ~ dnorm(0, 0.01)   #beta_rich_EnergyUse
  beta[7] ~ dnorm(0, 0.01)   #beta_poor_urb
  beta[8] ~ dnorm(0, 0.01)   #beta_rich_urb
  beta[9] ~ dnorm(0, 0.01)   #beta_poor_internet
  beta[10]~ dnorm(0, 0.01)   #beta_rich_internet

  # Prior for threshold
  threshold ~ dunif(min_threshold, max_threshold)

  # Define thresholds
  min_threshold <- 27000
  max_threshold <- 27001
}
"

#Normalization of covariates
preproc2 <- preProcess(CO2[,c(4:10)], method=c("range"))
norm2 <- predict(preproc2, CO2[,c(4:10)])

# Data preparation
data_list <- list(
  N = nrow(CO2),    # Number of data points
  co2percap = CO2$co2percap,
  EnergyUse = norm2$EnergyUse * (1-CO2$Lowcarbon_energy/100),
  GDP = norm2$GDP,
  pop = norm2$pop,
  internet = CO2$internet/CO2$pop,
  urb = CO2$urb/100,
  unGDP = CO2$GDP   #Un-normalized GDP to be compared with threshold
)

# Set the number of burn-in and iterations
n_iterations <- 5000

# Compile the model
jags_model <- jags.model(textConnection(model_string), data = data_list)

update(jags_model, 5000, progress.bar="none")

# Run the model
jags_output <- coda.samples(model = jags_model, variable.names = c(
  "beta",
  "threshold",
  "beta_gamma"

), n.iter = n_iterations, n.thin = 4, n.chains = 1)

gr=summary(jags_output)
gr

```


```{r}
mcmc_trace(jags_output,pars = c("beta[1]"))
mcmc_areas(jags_output,pars = c("beta[1]"),  prob = 0.95)
mcmc_trace(jags_output,pars = c("beta[2]"))
mcmc_areas(jags_output,pars = c("beta[2]"),  prob = 0.95)
mcmc_trace(jags_output,pars = c("beta[3]"))
mcmc_areas(jags_output,pars = c("beta[3]"),  prob = 0.80)
mcmc_trace(jags_output,pars = c("beta[4]"))
mcmc_areas(jags_output,pars = c("beta[4]"),  prob = 0.80)
mcmc_trace(jags_output,pars = c("beta[5]"))
mcmc_areas(jags_output,pars = c("beta[5]"),  prob = 0.95)
mcmc_trace(jags_output,pars = c("beta[6]"))
mcmc_areas(jags_output,pars = c("beta[6]"),  prob = 0.95)
mcmc_trace(jags_output,pars = c("beta[7]"))
mcmc_areas(jags_output,pars = c("beta[7]"),  prob = 0.95)
mcmc_trace(jags_output,pars = c("beta[8]"))
mcmc_areas(jags_output,pars = c("beta[8]"),  prob = 0.95)
mcmc_trace(jags_output,pars = c("beta[9]"))
mcmc_areas(jags_output,pars = c("beta[9]"),  prob = 0.95)
mcmc_trace(jags_output,pars = c("beta[10]"))
mcmc_areas(jags_output,pars = c("beta[10]"),  prob = 0.95)

```
